import{a as S,S as q,i as n}from"./assets/vendor-Do60_h77.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const $="55602979-87695c273b240492dacb11b66",R="https://pixabay.com/api/";async function h(e,o){return(await S.get(R,{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),L=document.querySelector(".load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(e){const o=e.map(({webformatURL:s,largeImageURL:c,tags:t,likes:r,views:a,comments:w,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${s}" alt="${t}" loading="lazy"/>
        </a>
        <div class="info">
          <p><span>${r}</span><span>Likes</span></p>
          <p><span>${a}</span><span>Views</span></p>
          <p><span>${w}</span><span>Comments</span></p>
          <p><span>${v}</span><span>Downloads</span></p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function b(){f.innerHTML=""}function m(){y.classList.add("is-visible")}function l(){y.classList.remove("is-visible")}function P(){L.classList.add("is-visible")}function u(){L.classList.remove("is-visible")}const M=document.querySelector(".form"),O=document.querySelector(".load-more");let p="",i=1,d=0;M.addEventListener("submit",async e=>{e.preventDefault();const o=e.target["search-text"].value.trim();if(o){p=o,i=1,b(),u(),m();try{const s=await h(p,i);if(d=s.totalHits,s.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),P(),s.hits.length*i>=d&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){n.error({message:`Something went wrong: ${s.message}`,position:"topRight"})}finally{l()}}});O.addEventListener("click",async()=>{i+=1,m();try{const e=await h(p,i);g(e.hits),x(),i*15>=d&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){n.error({message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{l()}});function x(){const e=document.querySelector(".gallery-item");if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}b();m();h(query).then(e=>{if(l(),e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits)}).catch(e=>{l(),n.error({message:`Something went wrong: ${e.message}`,position:"topRight"})});
//# sourceMappingURL=index.js.map
